name: hhgtn-fraud-detection
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python>=3.9,<3.13
  
  # Core ML & Data Science
  - numpy=2.2.3
  - pandas=2.3.1
  - scipy=1.16.2
  - scikit-learn=1.7.2
  
  # PyTorch Ecosystem
  - pytorch=2.8.0
  - torchvision>=0.19.0
  - pyg>=2.5.0
  
  # Graph & Network Analysis
  - networkx=3.3
  
  # Visualization
  - matplotlib=3.10.1
  - plotly>=5.18.0
  
  # Development Tools
  - pytest>=8.0.0
  - jupyter
  - ipykernel
  
  # Pip-only dependencies
  - pip
  - pip:
    - torch-geometric>=2.5.0
    - pyvis>=0.3.2
    - xgboost>=2.0.0
    - tensorboard>=2.16.0
    - wandb>=0.17.0
    - python-dotenv>=1.0.0
    - flask>=3.0.0
    - flask-cors>=4.0.0
    - pyarrow>=16.0.0
    - tqdm>=4.66.0
