# GCN Baseline Configuration
model: gcn
data_path: data/ellipticpp/ellipticpp.pt
out_dir: experiments/baseline/lite_gcn
epochs: 5
lr: 0.001
hidden_dim: 64
weight_decay: 0.00001
device: cuda
sample: 2000  # lite mode - sample 2000 nodes for quick testing
seed: 42